### ISSUE TITLE
Feature request: battery voltage

### ISSUE THREAD

**Issue by attah** [miikasda/harbour-skruuvi#8]
Many thanks for this great app! 
I now have 2 Ruuvis running, and it works great.

In troubleshooting one of them; i was asked to check the battery voltage - which apparently the official app can do.
Any chance that can be added to Skruuvi?

**Comment by miikasda** [comment]
Hi, thanks for the feature request! This has been on my mind too. Since others find it a useful feature as well, I'll add it this summer.

**Comment by attah** [comment]
Just tested. It works of course. Thanks!

Some thoughts about the layout: 
- The voltage and moves display on the main screen all but runs out of space on my 10 III - maybe consider putting it on another row.
- Also consider using secondary color, though maybe just for the mac address.
- It would be good to have the voltage and moves on the show/plot data screen too.

**Comment by miikasda** [comment]
Thanks for the comments! I wasn't completely happy with the UI layout either and will probably improve it before making a new release to harbour and Chum. I will also add the information to the "plot data" screen, great idea!
